---
title: "Bric-a-brac"
sidebar: false
---

A compendium of sundry miscellanea.

- [plot_birds_fixed.jl](jl/plot_birds_fixed.jl) -- A Julia Plots recipe, used to plot birds in the homework [Making birds fly](homework/fly.qmd)
- [VariationalLearning.jl](jl/VariationalLearning.jl) -- A Julia module that defines the `VariationalLearner` type and some functions to deal with such learners. See, in particular, [this homework solution](solutions/modules.qmd). To use this, execute the following (don't forget the dot before the module name, as this is a local module):

  ```{julia}
  #|eval: false
  include("VariationalLearning.jl")
  using .VariationalLearning
  ```

- [GridVL.jl](jl/GridVL.jl) -- A Julia module that implements a `VariationalLearner` on a grid space in Agents.jl. To use:

  ```{julia}
  #|eval: false
  include("GridVL.jl")
  using .GridVL
  ```

  If Julia complains about an "invalid redefinition of type VariationalLearner", this is because you have the older (non-spatial) type in memory. Exit your Julia session (or VSCode) and try again. Once the module has been successfully loaded, you can run the commands in the lecture on [structured populations](lectures/structured.qmd).

